version: '3.7'

services:
  app:
    stdin_open: true
    environment:
      - WATCHPACK_POLLING=true
    build:
      context: ./client
      dockerfile: Dockerfile.app
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./client
        target: /app
      - type: bind
        source: ./client/src/assets/Rules
        target: /app/Rules

  python:
      build:
        context: ./python
        dockerfile: Dockerfile.py
        args:
          no_cache: "true"
      ports:
        - "5000:5000"
      networks:
        - mysql_network
      volumes:
        - type: bind
          source: ./python
          target: /app
          #Esta linea es para compartir el reglamento guardado en en React con el contenedor de python
        - type: bind
          source: ./client/src/assets/Rules
          target: /app/Rules
  mysql :
      build:
        dockerfile: Dockerfile.db
        context: ./mysql
      container_name: mysql
      restart: always
      ports :
        - 23306:3306
      environment :
        MYSQL_DATABASE: "pasantiasfic"
        MYSQL_USER: "administrador"
        MYSQL_ROOT_PASSWORD: "passroot"
        MYSQL_PASSWORD: "passnormal"  
      volumes :
        - ./mysql/schemas:/var/lib/mysql:rw
      networks :
        mysql_network:
          aliases:
            - mysql_host
volumes:
  schemas: {}
networks:
  mysql_network :
    name: mysql_net
    driver: bridge
